version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"